### ISSUE TITLE
Enabling the code in Node-Red

### ISSUE THREAD

**Issue by nigobo** [TheThingSystem/node-telldus-live#8]
Hi!

I have tried to use your code in my Node Red installation with no success. I have noted my versions of Node Red/Node.js. And I can't seem to get your code to work. I hope that you can help me.

```
6 Jun 13:19:54 - [info] Node-RED version: v0.13.4
6 Jun 13:19:54 - [info] Node.js  version: v4.2.2
6 Jun 13:19:54 - [info] Linux 3.11.10-29-default x64 LE
```

I have tried to enable it by adding the code below to `settings.js` in the  `functionGlobalContext` part.

```
TelldusAPI:require("telldus-live")
```

and by adding `var TelldusAPI = require('telldus-live');` to the acctual function node and to a bunch of places in the `settings.js` 

When adding the `var TelldusAPI = require('telldus-live');` in the function node I get this error message.

![screen shot 2016-06-06 at 13 29 21]
(https://cloud.githubusercontent.com/assets/2266769/15820626/f6a94288-2bea-11e6-82e5-f960f6ffbc47.png)

And if i remove the `var TelldusAPI = require('telldus-live');` part I get this error message.

![screen shot 2016-06-06 at 13 32 04](https://cloud.githubusercontent.com/assets/2266769/15820647/1732284e-2beb-11e6-8e34-d3b21ed8f9a5.png)

I am not that familiar with Node.js but I hope to get starting using your module since I have a Tellstick Net.

Best regards,
Jocke

**Comment by steam0** [comment]
Please create a gist of all your code. Much easier to help you then.

**Comment by nigobo** [comment]
Thanks for the suggestion

1. My node-red-node-code (the code in the function node) https://gist.github.com/nigobo/1a212d827e58181f470dd85768b08304
2. My node-red settings.js https://gist.github.com/nigobo/7ac9a48ba38077f21734515c5c7f120f

**Comment by nigobo** [comment]
After some help in the Node-Red Google Group I got the code working by adding `tellduslive:require('telldus-live')` in `settings.js` in the `functionGlobalContect` section. 

Link to Node-Red Google group https://groups.google.com/d/topic/node-red/2--0xiYkXew/discussion
